format = "v1"

[metadata]
desc = "Official Arduino SDK image for Milk-V Duo (64M RAM, SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v1.1.4"

[[distfiles]]
name = "arduino-milkv-duo-sd-v1.1.4.img.zip"
size = 71598618
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/v1.1.4/arduino-milkv-duo-sd-v1.1.4.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "644d7bdd24ad8ecb222c1bba938813e88eadf21588fbabf8258fea37a4f88e82"
sha512 = "2d0cea3cb192a71e04956a619e1636fbcd2c287d9d7630e07ea3e8e8ae7f5d2501a864c947a13e818aece105e0ae4f2c00c96332dbbe245289a57aab44d94fef"

[blob]
distfiles = [
  "arduino-milkv-duo-sd-v1.1.4.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "arduino-milkv-duo-sd-v1.1.4.img"
