ruyi-entity = "v0"

related = ["arch:riscv64"]
unique_among_type_during_traversal = true

[uarch]
id = "spacemit-x60"
display_name = "SpacemiT X60"
arch = "riscv64"

[uarch.riscv]
# See: https://developer.spacemit.com/documentation?token=BWbGwbx7liGW21kq9lucSA6Vnpb
isa = "rv64imafdvc_sscofpmf_sstc_svinval_svnapot_svpbmt_zicbom_zicbop_zicboz_zicntr_zicond_zicsr_zifencei_zihintpause_zihpm_zfh_zfhmin_zkt_zba_zbb_zbc_zbs_zbkc_zvfh_zvfhmin_zvkt_zvl32b_zvl64b_zvl128b_zvl256b"
