ruyi-entity = "v0"

related = [
  "device-variant:orangepi-rv2@2g",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Armbian (xfce desktop) for Orange Pi RV2"
package_atoms = ["board-image/armbian-desktop-orangepi-rv2"]
