ruyi-entity = "v0"

related = [
  "device-variant:armbian-musepipro@generic",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Armbian for Muse Pi Pro"
package_atoms = ["board-image/armbian-musepipro"]
