ruyi-entity = "v0"

related = [
  "device-variant:bananapi-bpi-f3@sd",
]
unique_among_type_during_traversal = true

[image-combo]
display_name = "Bianbu Minimal for SpacemiT K1"
package_atoms = ["board-image/bianbu-minimal-spacemit-k1-sd"]
