format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo S v1.1.1-2024-0528 (SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.1"

[[distfiles]]
name = "milkv-duos-sd-v1.1.1-2024-0528.img.zip"
size = 61753217
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.1/milkv-duos-sd-v1.1.1-2024-0528.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7b644e893a8e86ab8cbc7d29de41cabe99e7eb126b69f59241c85822ccefb90d"
sha512 = "eb0180a7bf0116012755a895ce8a18a8042b53ec0994dabca653d5d87788c4c53349c173d6d6cc647e46e6d8250483544d98946c17ec3abd75e75f4bb209d4df"

[blob]
distfiles = [
  "milkv-duos-sd-v1.1.1-2024-0528.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duos-sd-v1.1.1-2024-0528.img"

# Manually created by Kosaka Reiya
