format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo S v1.1.2-2024-0801 (SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.2"

[[distfiles]]
name = "milkv-duos-sd-v1.1.2-2024-0801.img.zip"
size = 61835735
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.2/milkv-duos-sd-v1.1.2-2024-0801.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "e532a3486798a3a901f94443ca1ef528fbc724c1c17b595d0fb4c43ae4bc4b37"
sha512 = "e23a93c138ebfb9c6da2f32cacb5601e7d5cc5789d9b17baaf056175ac5051504536710b7f5b992d8feb2baaa118d783a7a36405ecdf1bf2a37565b58332821d"

[blob]
distfiles = [
  "milkv-duos-sd-v1.1.2-2024-0801.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duos-sd-v1.1.2-2024-0801.img"

# Manually created by Kosaka Reiya
