format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo S v2.0.1 (SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v2.0.1"

[[distfiles]]
name = "milkv-duos-musl-riscv64-sd_v2.0.1.img.zip"
size = 87915728
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk-v2/releases/download/v2.0.1/milkv-duos-musl-riscv64-sd_v2.0.1.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "1887e05d899a8dc0a4fb62622e16ae8012e00e46fd917f6662c958a63dc5d0ea"
sha512 = "ff31fdbcfaa545d4191df1ae3462b14c67be3c3fe74531dcba5a4cb4dcecf16facdfb2996b221d9f61daa35c2f46292906383fbe257a4264dc2476d027b32fd4"

[blob]
distfiles = [
  "milkv-duos-musl-riscv64-sd_v2.0.1.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duos-musl-riscv64-sd_v2.0.1.img"
