format = "v1"

[metadata]
desc = "Official OpenBSD 7.4 riscv64 live image"
vendor = { name = "OpenBSD", eula = "" }
upstream_version = "7.4"

[[distfiles]]
name = "install74.img"
size = 528482304
urls = [
  "https://ftp.openbsd.org/pub/OpenBSD/7.4/riscv64/install74.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "21b5f1077a7f1ecceb791e72df1787b293dc2555122f7ae16a441553fe15efbb"
sha512 = "9817375a03a99352a8bdad5647c0f29e0edd6ff98c5c4a762441230045bc2e9fde098ab79a7437050af3eb36487701f18e891fbff30ac5ca71cc4b439cfb7c95"

[blob]
distfiles = [
  "install74.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
live = "install74.img"
