format = "v1"

[metadata]
desc = "Official OpenBSD 7.6 riscv64 live image"
vendor = { name = "OpenBSD", eula = "" }
upstream_version = "7.6"

[[distfiles]]
name = "install76.img"
size = 528482304
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/OpenBSD/7.6/riscv64/install76.img",
  "https://cdn.openbsd.org/pub/OpenBSD/7.6/riscv64/install76.img",
  "https://ftp.openbsd.org/pub/OpenBSD/7.6/riscv64/install76.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "2c5a31d54662c7b711d67728fe96c6d763bb718f19d65049ca869b4e3c9c547f"
sha512 = "4392433835c912d9cca4dab788421f0cb0257d5c7c6ef781502006d551470e758e697ab23603bf2197f5c5d2da644b43b922b40a5f69a6f766172138dcbe9d6a"

[blob]
distfiles = [
  "install76.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
live = "install76.img"
