format = "v1"

[metadata]
desc = "Official OpenBSD 7.7 riscv64 live image"
vendor = { name = "OpenBSD", eula = "" }
upstream_version = "7.7"

[[distfiles]]
name = "install77.img"
size = 528482304
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/OpenBSD/7.7/riscv64/install77.img",
  "https://cdn.openbsd.org/pub/OpenBSD/7.7/riscv64/install77.img",
  "https://ftp.openbsd.org/pub/OpenBSD/7.7/riscv64/install77.img",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "54e2dabeb6c8a219d9cc0080abaef263e0bf1f9223e67a1f2f5b0a3a4c59969b"
sha512 = "a769cee2a2f9db4b0286c91ce56cfbe42bdab9d8d7a35d0f2fc3a5a4555620967df2589357665ab32ebcab6917599b5ea21674caabceee5218fe07d2ed3cd509"

[blob]
distfiles = [
  "install77.img",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
live = "install77.img"
