format = "v1"

[[distfiles]]
name = "u-boot-with-spl-lpi4a-main.20250420.bin"
size = 1032312
urls = ["https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20250420/u-boot-with-spl-lpi4a-main.bin", ]
restrict = ["mirror", ]

[distfiles.checksums]
sha256 = "a9b57cfbd4ffaa5031aa39e1e22eaa8169654712e41f7ad5ae453d22da8e0807"
sha512 = "fd2389e3e3a8198f56a56711d8f662ab07c0f8851927111ae4b6e5d1e22cd66419d0ea5e362eb1622ebd0b424480c10dfda1833494a1b30e203b2724d33d987c"

[metadata]
desc = "U-Boot image for LicheePi 4A (8G RAM) and RevyOS 20250420"
upstream_version = "20250420"

[[metadata.service_level]]
level = "good"

[blob]
distfiles = ["u-boot-with-spl-lpi4a-main.20250420.bin", ]

[provisionable]
strategy = "fastboot-v1(lpi4a-uboot)"

[metadata.vendor]
name = "PLCT"
eula = ""

[provisionable.partition_map]
uboot = "u-boot-with-spl-lpi4a-main.20250420.bin"

# Manually created by Kosaka Reiya
