format = "v1"

[metadata]
desc = "Official Ubuntu 23.10 Server image for SiFive HiFive Unmatched"
vendor = { name = "Ubuntu", eula = "" }

[[distfiles]]
name = "ubuntu-23.10-preinstalled-server-riscv64+unmatched.img.xz"
size = 1083609240
urls = [
  "https://mirror.tuna.tsinghua.edu.cn/ubuntu-cdimage/releases/mantic/release/ubuntu-23.10-preinstalled-server-riscv64+unmatched.img.xz",
  "https://cdimage.ubuntu.com/releases/23.10/release/ubuntu-23.10-preinstalled-server-riscv64+unmatched.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "5c300b9fff78f5d86fec06787e833573220165aeb310a8f1b5c56ca888bc91c2"
sha512 = "ca136843a79c55b5ae00e7de6f0a2a3b1039af8092006e9d48c4e950b267c4793ff5d45cc660b392ccaf9b2fbb6c85afdd27ee36141643f7d5ae46b982fd666c"

[blob]
distfiles = [
  "ubuntu-23.10-preinstalled-server-riscv64+unmatched.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "ubuntu-23.10-preinstalled-server-riscv64+unmatched.img"
