format = "v1"

[metadata]
desc = "Official Bianbu Desktop v2.0.4 for SpacemiT K1, SD image"
vendor = { name = "SpacemiT", eula = "" }
upstream_version = "v2.0.4"

[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.img.zip"
size = 2632497569
urls = [
  "https://archive.spacemit.com/image/k1/version/bianbu/v2.0.4/bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "436ae1db2c8ca4d860e726f2ff7ed6b0da4947e9b67ee8fac6db263d1625e03f"
sha512 = "98c41db327ec78607d9f9ce67eddc2b2340f65cbbbb45b9f840faef1fc2e285de8c509f816fe9fce6cac4e893b02ae087a7e04f87e644ddca3d607a337b2cf32"

[blob]
distfiles = [
  "bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.img"
