format = "v1"

[metadata]
desc = "Official Arduino SDK image for Milk-V Duo (256M RAM, SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v1.1.4"

[[distfiles]]
name = "arduino-milkv-duo256m-sd-v1.1.4.img.zip"
size = 85579241
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/v1.1.4/arduino-milkv-duo256m-sd-v1.1.4.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "1e7fb9f36c32c1ef25c183477b1a9d1e5d9240858a030463e332d3daecc94ada"
sha512 = "39e3de34ca1f1c6a9e1947a315c2f98efd79d739952c31001444041b973243b73dfb2a29cccbadc7cc17c834c52955a944b30a42234af01ab959a16a5627d109"

[blob]
distfiles = [
  "arduino-milkv-duo256m-sd-v1.1.4.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "arduino-milkv-duo256m-sd-v1.1.4.img"
