format = "v1"

[metadata]
desc = "Official Arduino SDK image for Milk-V Duo (256M RAM, SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.2"

[[distfiles]]
name = "arduino-milkv-duo256m-sd-v1.1.2-2024-0801.img.zip"
size = 81614369
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.2/arduino-milkv-duo256m-sd-v1.1.2-2024-0801.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "e79aaae4d7e9b37b40885dd6eb016d57a3f6d4154ca08e7d468909cb64d1dd58"
sha512 = "123733a0083226adfae88846629a0aa8c20c3d512033149df70c3622eefbfd004acfe9c1a0bfcf3a3b6a09249fd27eacc4308256cd1c7899b0802880a69cccb8"

[blob]
distfiles = [
  "arduino-milkv-duo256m-sd-v1.1.2-2024-0801.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "arduino-milkv-duo256m-sd-v1.1.2-2024-0801.img"
