format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (64M RAM) v1.0.9-2024-0226"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.0.9"

[[distfiles]]
name = "milkv-duo-v1.0.9-2024-0226.img.zip"
size = 60707633
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.0.9/milkv-duo-v1.0.9-2024-0226.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "ad9c404a2026e9e68ba3bd24deec94324d85ad17cd2cf62a25fd238fd7a6067c"
sha512 = "f21977168cffdcca1f93f8ac4a1cd72f61108f3ec8946a63e0185fef1d6fd80e6badb110139835904a7ab41e87886e3a79988246fb5b85070bef254973dbf954"

[blob]
distfiles = [
  "milkv-duo-v1.0.9-2024-0226.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo-v1.0.9-2024-0226.img"

# Manually created by Kosaka Reiya
