format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (64M RAM) v1.1.1-2024-0528"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.1"

[[distfiles]]
name = "milkv-duo-v1.1.1-2024-0528.img.zip"
size = 62510518
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.1/milkv-duo-v1.1.1-2024-0528.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "6601fdc71a6e94485ec12bf004d19b6654171f3c59cdddb71544ce5187c9e5e4"
sha512 = "1124d63572ab5cfd77c71ba3a6b28c0782b3ce32d8aa79f889fd89e9774377af31a55e7319bd4bfab98ded05c5f7f0d5d30a7944b13aa3a454afad2311bbfc13"

[blob]
distfiles = [
  "milkv-duo-v1.1.1-2024-0528.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo-v1.1.1-2024-0528.img"

# Manually created by Kosaka Reiya
