format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (64M RAM) v1.1.0-2024-0410"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.0"

[[distfiles]]
name = "milkv-duo-v1.1.0-2024-0410.img.zip"
size = 61986488
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.0/milkv-duo-v1.1.0-2024-0410.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "27b052cbf6de97b4a9093838b9a3d66e1155831c743e0ad354567032bd2b2b3f"
sha512 = "619c38e8207d80a75126da30ba3d1cd6446713ab383babdbfc8713561d3291e6e9ad54fb9a5cfc40616a5be3842b4065fc40eefd9e738e2477775e2261b15bb9"

[blob]
distfiles = [
  "milkv-duo-v1.1.0-2024-0410.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo-v1.1.0-2024-0410.img"

# Manually created by Kosaka Reiya
