format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (256M RAM) v1.0.9-2024-0226"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.0.9"

[[distfiles]]
name = "milkv-duo256m-v1.0.9-2024-0226.img.zip"
size = 72683814
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.0.9/milkv-duo256m-v1.0.9-2024-0226.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "b5b3ca8cb58d0726a4dfd4bfce52bd17abd3bc9b552f9700143f755a98eb0ca9"
sha512 = "6f6356f46989a45f8086b0f5fc8685051fecc8b4cc991d6b61244582b062150bcc140fb1bc97319c764efca7ea2faabeb91e72dc9cac42b9e48df1d851ba13ce"

[blob]
distfiles = [
  "milkv-duo256m-v1.0.9-2024-0226.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo256m-v1.0.9-2024-0226.img"

# Manually created by Kosaka Reiya
