format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (256M RAM) v1.1.0-2024-0410"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.0"

[[distfiles]]
name = "milkv-duo256m-v1.1.0-2024-0410.img.zip"
size = 74025943
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.0/milkv-duo256m-v1.1.0-2024-0410.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f80a629dd4c835ad09ca33f2431b948a28db0280e7abecbf22defcd57a1aa3ea"
sha512 = "0845aa141c1cffd8df06a6e9b9a32335d63d0794d0ce66dfbf67abbc19064105633fe1a5c1ae83e2e275e5f03a3e27314799e3d367977ac6079b6035f012dc36"

[blob]
distfiles = [
  "milkv-duo256m-v1.1.0-2024-0410.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo256m-v1.1.0-2024-0410.img"

# Manually created by Kosaka Reiya
