format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (256M RAM) v1.1.2-2024-0801"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "Duo-V1.1.2"

[[distfiles]]
name = "milkv-duo256m-sd-v1.1.2-2024-0801.img.zip"
size = 81191387
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk/releases/download/Duo-V1.1.2/milkv-duo256m-sd-v1.1.2-2024-0801.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "da520d503a4ba634492a231ddd5fc509d5f82c1f8bf28e6fe133b081b58dbcc6"
sha512 = "03f8360cff33702b4526bde410f89635cfd26561d2a20dd67795186bae1ba74d10a1f3f621dd4f11f8073b5dc191ea270cee096474b9a10af8da558198986ac2"

[blob]
distfiles = [
  "milkv-duo256m-sd-v1.1.2-2024-0801.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo256m-sd-v1.1.2-2024-0801.img"

# Manually created by Kosaka Reiya
