format = "v1"

[metadata]
desc = "Official Buildroot SDK image for Milk-V Duo (256M RAM) v2.0.1"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "v2.0.1"

[[distfiles]]
name = "milkv-duo256m-musl-riscv64-sd_v2.0.1.img.zip"
size = 81091750
urls = [
  "https://github.com/milkv-duo/duo-buildroot-sdk-v2/releases/download/v2.0.1/milkv-duo256m-musl-riscv64-sd_v2.0.1.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8feddefb8f588f390ff8a2a3039b2e3444666e78b105d6845c16f2963eff590c"
sha512 = "f14b4ee9dc9ab313ba5662e0640a6814961f631f8af8ef6bbee060fe45108437b099db1d3fe1a54611ad69f74d56d26f534e409406e271148d02a45d33bfd15a"

[blob]
distfiles = [
  "milkv-duo256m-musl-riscv64-sd_v2.0.1.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "milkv-duo256m-musl-riscv64-sd_v2.0.1.img"
