format = "v1"

[metadata]
desc = "Official Ubuntu 22.04.5 Server image for SiFive HiFive Unmatched"
vendor = { name = "Ubuntu", eula = "" }
upstream_version = "22.04.5"

[[distfiles]]
name = "ubuntu-22.04.5-preinstalled-server-riscv64+unmatched.img.xz"
size = 856038872
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cdimage/releases/22.04/release/ubuntu-22.04.5-preinstalled-server-riscv64+unmatched.img.xz",
  "https://cdimage.ubuntu.com/releases/22.04/release/ubuntu-22.04.5-preinstalled-server-riscv64+unmatched.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4281edf7bff64d7ac4f8bae5b1ded7b66937ec51dd62ddfdbc7851e5c8c68ecb"
sha512 = "08ec037f50ebfa434785fae1c17df3e805abfea13ac26efdcdfaf65e8bfc4ddbefa002efc485d2512ae68fb93932e606ebc1d43a51d6ad9106f9652ac4a98094"

[blob]
distfiles = [
  "ubuntu-22.04.5-preinstalled-server-riscv64+unmatched.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "ubuntu-22.04.5-preinstalled-server-riscv64+unmatched.img"
