ruyi-entity = "v0"

related = [
    "device-variant:bananapi-bpi-f3@sd",
    "device-variant:bananapi-bpi-f3@emmc",
]
unique_among_type_during_traversal = true

[device]
id = "bananapi-bpi-f3"
display_name = "BananaPi BPI-F3"
