format = "v1"
[[distfiles]]
name = "revyos-pioneer-20241230-212249.img.zst"
size = 2070581519
urls = [ "https://mirror.iscas.ac.cn/revyos/extra/images/sg2042/20241230/revyos-pioneer-20241230-212249.img.zst",]
restrict = [ "mirror",]

[distfiles.checksums]
sha256 = "77edd1b56f41ebdd35f95aa2876e14e792a47ba5adc570a7be9d0964fc883ba1"
sha512 = "ec2df0aeb46c621042eaa458b25443962c0d221ce93ee85f9b0346f3955c07f0120caf49df5d74ec22ed6a5c98bf152c0886574ab34b23fda74203a4902d3c03"

[metadata]
desc = "RevyOS 20241230 image for Milk-V Pioneer Box with SG2042"
upstream_version = "20241230"
[[metadata.service_level]]
level = "good"

[blob]
distfiles = [ "revyos-pioneer-20241230-212249.img.zst",]

[provisionable]
strategy = "dd_v1"

[metadata.vendor]
name = "milkv-pioneer"
eula = ""

[provisionable.partition_map]
disk = "revyos-pioneer-20241230-212249.img.zst"

# This file is created by program Sync Package Index inside support-matrix
# Run ID: 14534401353
# Run URL: https://github.com/wychlw/support-matrix/actions/runs/14534401353
