format = "v1"

[metadata]
desc = "Official OpenWRT 23.05.2 image for SiFive Unmatched"
vendor = { name = "OpenWrt", eula = "" }
upstream_version = "23.05.2"

[[distfiles]]
name = "openwrt-23.05.2-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz"
size = 8257899
urls = [
  "https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/23.05.2/targets/sifiveu/generic/openwrt-23.05.2-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
  "https://downloads.openwrt.org/releases/23.05.2/targets/sifiveu/generic/openwrt-23.05.2-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "4a6fd0c06fa830cabbe1c92afce38c00310ab9e055b0cab21f332b6c96408263"
sha512 = "c7d828d4c81120eeea9232cacd7261cf67e4bb1b5e3f61de52a17f7932a1a8500dd242c596cc847f6943b1ee790507a364dffa87f1d3bec48f9ea12699e986b5"

[blob]
distfiles = [
  "openwrt-23.05.2-sifiveu-generic-sifive_unmatched-ext4-sdcard.img.gz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "openwrt-23.05.2-sifiveu-generic-sifive_unmatched-ext4-sdcard.img"
