format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.699 image for Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.699"

[[distfiles]]
name = "Armbian_26.2.0-trunk.699_Musepipro_forky_current_6.18.21_minimal.img.xz"
size = 311517604
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.699/Armbian_26.2.0-trunk.699_Musepipro_forky_current_6.18.21_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "c552e3ace9c459a8ed615f0bac2dcc295f2e985648bd83209d8fa92881cf9b1b"
sha512 = "161a8ebe9ab3eef98f17fa2fd00f15323bef66b6467ae80d3eea20899c0c460c12bfe3a25a6a3dc9c4623dcd530effdc2f8fb17c33574971148bb2bbdfd2c80d"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.699_Musepipro_forky_current_6.18.21_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.699_Musepipro_forky_current_6.18.21_minimal.img"
