format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.679 image for Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.679"

[[distfiles]]
name = "Armbian_26.2.0-trunk.679_Musepipro_forky_current_6.18.21_minimal.img.xz"
size = 312590380
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.679/Armbian_26.2.0-trunk.679_Musepipro_forky_current_6.18.21_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f824bbd69eee71ede6bc3d1c36ad8141e5f23c5885ee5af789d988d58f976344"
sha512 = "1ff6c12141328ef07a5ed0c0f1d5dbba66c9ac23fdd1f5c202b3dbcfd64bb0b6b6926e4adde47532e41e87d2400354588eaa68bee3b345dc51cccff20db46125"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.679_Musepipro_forky_current_6.18.21_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.679_Musepipro_forky_current_6.18.21_minimal.img"
