format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.707 image for Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.707"

[[distfiles]]
name = "Armbian_26.2.0-trunk.707_Musepipro_forky_current_6.18.21_minimal.img.xz"
size = 325656440
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.707/Armbian_26.2.0-trunk.707_Musepipro_forky_current_6.18.21_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "f63e1e32bd5ad13e01aacf724f438c30c9115e2e6498b248840ab466f3d01098"
sha512 = "34e2432416c9aeadbcd68a504671cfe70f5903074f518930f0b7b45d06cfb493a2803cbf059c6969ea26968ef461c0bb3a3e446ba5caddec3666e2b651d7e1be"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.707_Musepipro_forky_current_6.18.21_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.707_Musepipro_forky_current_6.18.21_minimal.img"
