format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.715 image for Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.715"

[[distfiles]]
name = "Armbian_26.2.0-trunk.715_Musepipro_forky_current_6.18.22_minimal.img.xz"
size = 325301680
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.715/Armbian_26.2.0-trunk.715_Musepipro_forky_current_6.18.22_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "7192c8553e4db3a3a5cb0ca2e441a42150d8ea89f0306b7d1bdfafff43d65264"
sha512 = "2ee91393db4a9d7d899da155e47d6853513fad1503e70eb6b978b529a832fde54f71d91958da430c1ee636f594788bf5ee244a7425c3f089f465cf1bdc8f8ab6"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.715_Musepipro_forky_current_6.18.22_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.715_Musepipro_forky_current_6.18.22_minimal.img"
