format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.716 image for Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.716"

[[distfiles]]
name = "Armbian_26.2.0-trunk.716_Musepipro_forky_current_6.18.22_minimal.img.xz"
size = 313856316
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.716/Armbian_26.2.0-trunk.716_Musepipro_forky_current_6.18.22_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "8fe6c30ea01ff2b715c85c2bddc9ae3e415fba6c93c51eadca1d0a85a0d6d633"
sha512 = "16ccebb59cfa2a8e4dc69ac3c79f91064e91cb2b80f313aa2fc312a6a35cf9d63e9a0ed22b957de44d0af5d1d5a65c8ca39d1a2d5ea8c3f7a7a79854177fc071"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.716_Musepipro_forky_current_6.18.22_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.716_Musepipro_forky_current_6.18.22_minimal.img"
