format = "v1"

[metadata]
desc = "Armbian 26.2.0-trunk.808 image for SpacemiT Muse Pi Pro"
vendor = { name = "Armbian", eula = "" }
upstream_version = "26.2.0-trunk.808"

[[distfiles]]
name = "Armbian_26.2.0-trunk.808_Musepipro_forky_current_6.18.24_minimal.img.xz"
size = 299784412
urls = [
  "https://github.com/armbian/os/releases/download/26.2.0-trunk.808/Armbian_26.2.0-trunk.808_Musepipro_forky_current_6.18.24_minimal.img.xz",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "5731ca02fb5102caf9ae0c092e2575d45da00e37c9c876f22f43ac40d44c0f0b"
sha512 = "0f8ea03b99256b9dfc660d56bd6631ef9586285a66ede1920610e7965390bdc90a2c8c841575c8725d11f5bf502f6f7aebb2e421831392632c961e22bdaad292"

[blob]
distfiles = [
  "Armbian_26.2.0-trunk.808_Musepipro_forky_current_6.18.24_minimal.img.xz",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "Armbian_26.2.0-trunk.808_Musepipro_forky_current_6.18.24_minimal.img"
