format = "v1"

[metadata]
desc = "Official Debian Desktop SDK v3.6.1 image for Milk-V Mars CM v1.0.5 (SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "V1.0.5"

[[distfiles]]
name = [
  "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.5.img.zip",
]
size = 1216117229
urls = [
  "https://github.com/milkv-mars/mars-buildroot-sdk/releases/download/V1.0.5/mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.5.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "5a5456e3e8a34e7ad907a11922085732bfdf342dabbf9f1b489b816699627047"
sha512 = "9e842d5042fda932282c79ce7ca85519deabf23eb8dc57320494c94c4f338e1276460fe3fe42994cc7558e91af35d69a630b5fdc4d6a7907b6c32b110fef990e"

[blob]
distfiles = [
  "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.5.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.5.img"
