format = "v1"

[metadata]
desc = "Official Debian Desktop SDK v3.6.1 image for Milk-V Mars CM v1.0.6 (SD card)"
vendor = { name = "Milk-V", eula = "" }
upstream_version = "V1.0.6"

[[distfiles]]
name = "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.6.img.zip"
size = 1371879672
urls = [
  "https://github.com/milkv-mars/mars-buildroot-sdk/releases/download/V1.0.6/mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.6.img.zip",
]
restrict = ["mirror"]

[distfiles.checksums]
sha256 = "aa6dbfed7a0bdcc239284dd9a1ce50a9227fa5341934f0696ec84441eb68a3ee"
sha512 = "6f4a8991920f097ba3b52fa9b4f1164a3d1824dc6ff802aaf622c16a093b5da71cd79ffd9d8d56172c69e25679d172aedc60d35917dfbfde10b11a54993e4934"

[blob]
distfiles = [
  "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.6.img.zip",
]

[provisionable]
strategy = "dd-v1"

[provisionable.partition_map]
disk = "mars-cm_debian-desktop_sdk-v3.6.1_cm4-io-board_sdcard_v1.0.6.img"
