name: Format-manifest checks

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - packages/board-image/**
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - packages/board-image/**

jobs:
  format-manifest:
    name: format-manifest test
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: packages-index

      - name: Install ruyi
        id: setup
        uses: ruyisdk/setup-ruyi-action@v1
        with:
          ruyi-version: beta

      - name: Configure ruyi
        run: |
          ruyi config set repo.local "$(realpath ./packages-index)"
          ruyi version
          ruyi telemetry consent

      - name: Check formatting of board-image files
        run: |
          ruyi admin check --check format --repo ./packages-index --only-packages --category-is board-image

      - name: Test data structure
        run: |
          ruyi admin check --check parse --repo ./packages-index

      - name: Post Install ruyi
        if: ${{ always() && steps.setup.conclusion == 'success' }}
        run: ruyi telemetry upload
